### PR TITLE
Add option for extra libs for examples

### PR DESCRIPTION
**Pull request by jolting**
This builds now
---

I acknowledge to have:
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`doc/doxygen-pages/changeLog_doc.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by jolting** [comment]
I'm not sure if this is the best approach. I was also wondering if there is a way to add the generated cmake files to .gitignore

**Comment by jlblancoc** [comment]
> I was also wondering if there is a way to add the generated cmake files to .gitignore

I know it seems redundant to include in git all CMakeLists.txt files for examples, when they can be dynamically generated, but it's done like that for two main reasons: (1) the most important is allowing users to directly copy/download/whatever an example subdirectory and build it **as is** with cmake after installing MRPT via apt-get or Windows installers; (2) I'm less sure of this one, but I don't feel comfortable modifying the SOURCE_DIR of CMake... I think that we should support building as if the the source code directories were read-only, just in case that's actually the case somewhere (?).

> I'm not sure if this is the best approach. 

Hmm... I see the problem. Probably it's better to add OpenNI2 libraries as CMake PUBLIC link dependencies. I'll try to test that approach, but won't be before late afternoon (CET time!), so let me know if you tried it first.

Cheers!

**Comment by jolting** [comment]
Perhaps a custom target with a PUBLIC link dependency. I'd hate to taint one of the real library targets.

**Comment by jlblancoc** [comment]
Let's keep this one open after #651, just to see if I can find an alternative "cleaner" solution with the PUBLIC interface way...

**Comment by jolting** [comment]
Rebased for easier comparison

**Comment by jlblancoc** [comment]
Thanks! 

I think the easier is to move these three examples to `doc/mrpt_*_examples/` together with other "special" examples, then modify their CMake files to do a pkg_config-search for openni2 in a proper way... 

Will try to do it later tonight.

**Comment by jlblancoc** [comment]
Closed after: https://github.com/MRPT/mrpt/commit/8f2bbd99eb2d758c0f2103e65f5c1a91e89403d9

**Pull request closed without merging**
