### PR TITLE
GSoC 2017 (LisGein)

### PR DESCRIPTION
**Pull request by LisGein**
## Changed apps/libraries
* robot-map-gui
* created mrpt::gui::CGlCanvasBase, and mrpt::gui::CQtGlCanvasBase

## PR Description
I have developed a new GUI application based on Qt 5.5. It is able to load data in 
Also, I created the base class for CMyGLCanvasBase and CQtGlCanvasBase, and refactored it.
---

I acknowledge to have:
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`doc/doxygen-pages/changeLog_doc.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-..) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by jolting** [comment]
@jlblancoc Many white space conflicts due to the Nuke merge.

`git merge lisgein/mrpt-2.0-devel -Xignore-all-space` will solve many of those conflicts. There are still a fair amount of conflicts.

**Comment by LisGein** [comment]
Yes, I replaced spaces to tabs, because it is written in "C ++ programming style for MRPT".

**Comment by jolting** [comment]
Understood. The tabs look correct, but the merge will require a little bit of work.

**Comment by jlblancoc** [comment]
@LisGein 
> Yes, I replaced spaces to tabs, because it is written in "C ++ programming style for MRPT".

Since your app is already into `master`, I think it'll be a good idea to do the merge now instead of waiting until the end of GSoC (then, do another final PR). 

Please, don't make (many) changes during the next ~24 hours or so, so it's easy for you to catch up after we accept the merge. When done, we'll discuss how to get your fork in synch with this original repo, so you can use the clang-format tool to avoid more formatting conflicts. 

@jolting :
>  git merge lisgein/mrpt-2.0-devel -Xignore-all-space will solve many of those conflicts. 

Another classic Hunter's git black magic ! will use it for sure. 
Also, I'm unsure about whether we have conflicts outside of the subdirectories Lis has changed... Perhaps a cherry-pick (or other more arcane trick) will do the job; but hopefully something that saves us from solving (again!) all those conflicts.

Will try to do it later tonight...

**Comment by jlblancoc** [comment]
Ok, I see... the conflicts are all real! Your improvements to the area of the generic GlCanvas in mrpt::gui made you to update **many** files, apart of your "robot GUI" app directory!! Good :+1: 

Still manually fixing the conflicts... will update here when done.

**Comment by jlblancoc** [comment]
Merged! :+1: 

Still has to thoroughly test your new code, but at least all conflicts are solved now. 

How to avoid more conflicts from now on? Please, @LisGein see the [instructions](https://github.com/MRPT/mrpt/blob/master/doc/ClangFormat.md#comply-new-code-with-clangformat) on passing the clang-format tool to the new code you write from now on. 

How to synch your fork with master? If you have not done any further changes, perhaps the simplest way is to delete your fork and re-fork again... Give us ~24 hours to make more tests and be sure all the required fixes are applied to `master` first, ok? 
Also, @jolting may offer you a less dramatic way of syncing your fork?

So far... thanks, you did a great job!

**Pull request merged**
