### PR TITLE
Added a new class CClearanceGrid in CParamterizedTrajectoryGenerator.h

### PR DESCRIPTION
**Pull request by chatrasen**
Yet to write the implementations of the saving and loading to file functions for this new grid. Remaining definitions have been implemented in the cpp file

### CODE REVIEW

**Comment by chatrasen** [comment]
What do these checks indicate? The code is compiling fine on my pc

**Comment by jlblancoc** [comment]
No worries, that error seems from travis, is not your fault. Will take a
closer look at your code later and will come back to you. Thanks for
contributing!! :-)

-----
Escrito desde Zapatófono, disculpe la brevedad.

**Comment by chatrasen** [comment]
Ok.. I have added some more commits now.. Have a look at them as well :)

**Comment by jlblancoc** [comment]
@chatrasen : I will close this PR, please reopen a new one against the newly-created branch `nav-devel`, so we don't touch `master` until all new code and apps work smoothly after this change. Thanks!

**Pull request closed without merging**
