### PR TITLE
Add CCACHE_SLOPPINESS=pch_defines,time_macros

### PR DESCRIPTION
**Pull request by jolting**
cotire recommends this for ccache

I acknowledge to have: 
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`docs/doxygen-pages/changelog.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by jlblancoc** [comment]
Shouldn't this be also merged into the add-cotire branch first?

**Comment by jolting** [comment]
Wasn't sure about potential merge conflicts with the new test matrix.

**Comment by jlblancoc** [comment]
I think the new env should be appended at the right hand side of each env entry in the new yaml entries...

**Comment by jolting** [comment]
Since add-cotire doesn't have ccache in the travis.yml yet, it didn't make sense to change it in that branch.

**Comment by jlblancoc** [comment]
Ah, you're right! Will add it when back to my computer.thanks

**Pull request merged**
