### PR TITLE
Camera Calib application fixes

### PR DESCRIPTION
**Pull request by mangi020**
**mrpt->apps->camera_calib** 
*   *A refined version of the camera calib application* ...
* [(*Link to video*)](https://www.youtube.com/watch?v=06bB_Qjo7HU) 

I acknowledge to have: 
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`docs/doxygen-pages/changelog.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by jolting** [comment]
@mangi020 Can you merge MRPT/mrpt master into mangi020/mrpt master, so that Travis can test the build on your master branch. Your branch has some build failures which I believe are already fixed.

**Comment by jlblancoc** [comment]
Thanks, @mangi020 ! I'll create a new PR in a temporary branch as a quick workaround about what @jolting says, ok? Then I'll merge that one after testing, but from the video it looks great... thanks for keeping contributing ;-)

**Comment by jlblancoc** [comment]
Actually... I guess that there must me some cleaner way of doing this, so I invoke @jolting 's Git mastership for advising ;-) 

This [merge commit](https://github.com/mangi020/mrpt/commit/e55bd258da6836f51f5e0eff284aed2bf6256ea1) in the fork is huge, as explained by it being a merge after an old synch (see [graph](https://github.com/MRPT/mrpt/network)). 

Do you know of any other way in which to efficiently merge @mangi020 's changes ??

**Comment by jolting** [comment]
@mangi020. Look at my pull request and look at yours. This git history is more complicated than it has to be. Consider rebasing.

**Comment by jlblancoc** [comment]
Closing, after accepting the alternative in #331.

**Pull request closed without merging**
