### PR TITLE
Output tests to bin dir

### PR DESCRIPTION
**Pull request by jolting**
Fixes appveyor

### CODE REVIEW

**Comment by jlblancoc** [comment]
I just saw it, yep... 
There was a "delayed load" command in hwdrivers related to libpcap, but it should only be enabled if pcap is found: https://github.com/MRPT/mrpt/blob/master/libs/hwdrivers/CMakeLists.txt#L193-L201
Perhaps a pragma link...

**Comment by jlblancoc** [comment]
https://github.com/MRPT/mrpt/blob/master/libs/hwdrivers/src/CIMUXSens_MT4.cpp#L316-L320

https://github.com/MRPT/mrpt/blob/master/libs/hwdrivers/src/CIMUXSens.cpp#L45-L48

**Comment by jlblancoc** [comment]
Right. Then, my only suspects are the two pragmas in the comment above: 
WinUsb.dll
Setup.dll

Perhaps WinUSB.dll would make sense to be something a virtual container may be stripped off (?).

**Comment by jolting** [comment]
What about assimp?

**Comment by jlblancoc** [comment]
Try please adding a commit disabling both XSens 3 & 4... if that fixes the issue we'll have a positive finding.

**Comment by jolting** [comment]
hwdrivers maps nav obs opengl slam and topography depend on assimp. The rest of the tests don't. I think thats why hwdriver is the first one to fail. assimp dll is missing when those tests are running.

**Pull request merged**
