### PR TITLE
use std::visit()

### PR DESCRIPTION
**Pull request by jlblancoc**
Fixes mapbox's `t.match()` ==> `std::visit()`.

PS: First test after setting mrpt/master as a Github "protected branch". Travis CI (and only Travis) being green is now a pre-requisite for merging.

### CODE REVIEW

**Comment by jolting** [comment]
Clang is still angry

**Comment by jolting** [comment]
https://bugs.llvm.org/show_bug.cgi?id=33222

**Comment by jolting** [comment]
We'll probably need to install clang-7.0 in the container from here:
http://apt.llvm.org

**Comment by jlblancoc** [comment]
Ok, thanks for investigating the bug!
I'll try it in this branch...

**Comment by jlblancoc** [comment]
clang-7 still fails with the same error... since it's a libstdc++ thing, obviously :-(

**Comment by jlblancoc** [comment]
What do you think about a custom version of STD visit as a workaround?

**Comment by jolting** [comment]
I was thinking the same thing.

**Comment by jlblancoc** [comment]
@jolting I spent a few hours writing my own visit(), just to find out that it works fine on gcc but fails with the same error in clang (!!). 

I'm afraid the only solution at this point is disabling variant for clang for a __GLIBCXX__ older than the current version... :-(

**Comment by jlblancoc** [comment]
@jolting feel free of merging if travis is happy after the last commit. Night!

**Comment by jolting** [comment]
That's fair. Write variable is not as useful as read variant.

Good night.

**Pull request merged**
