### PR TITLE
Load plugin from cmdline

### PR DESCRIPTION
**Pull request by jolting**
I acknowledge to have: 
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`docs/doxygen-pages/changelog.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

Added to rawlog-viewer and ptg-configurator

### CODE REVIEW

**Comment by jlblancoc** [comment]
I merged it, but I think we'll have to add "dl" as "-l" argument to the linker as well...

**Comment by jolting** [comment]
Those now reside in libc on Linux, but it shouldn't hurt. For historical reasons, it probably is a good idea.

**Comment by jolting** [comment]
@jlblancoc For feature parity on Windows LoadLibrary should work.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms684175(v=vs.85).aspx

**Comment by jlblancoc** [comment]
I knew I had to add `dl` recently for some reason... :-( 

All PPA builds failed, look for "error:" in, for example:
https://launchpadlibrarian.net/294061337/buildlog_ubuntu-xenial-armhf.mrpt_1%3A1.5.0~snapshot20161119-0309-git-6895c2d6-xenial-1~ppa1~xenial_BUILDING.txt.gz

**Pull request merged**
