### PR TITLE
Organize Travis builds into stages

### PR DESCRIPTION
**Pull request by jolting**

### CODE REVIEW

**Comment by jlblancoc** [comment]
Great idea! 
It seems there is plenty of room (time) left in stage 1, so we could try building some more libs [up the tree of dependencies](http://mrpt.ual.es/reference/master/), for example, mrpt-slam, to leave more free time in next stages.

**Comment by jlblancoc** [comment]
Ok, I saw you commit... we are really in synch XD

**Comment by jolting** [comment]
I can't see a limit on dockerhub, so it made sense.

**Comment by jlblancoc** [comment]
It works like a charm! 🥇

**Comment by jolting** [comment]
Hopefully, travis builds will be reliable now.

**Pull request merged**
