### PR TITLE
This pull request fixes the issues for the opencv version in #586

### PR DESCRIPTION
**Pull request by raghavendersahdev**
## Changed apps/libraries

* modified CFeatureExtraction_AKAZE.cpp
* modified CFeatureExtraction_LATCH.cpp
* modified CFeatureExtraction_LSD_BLD.cpp
* updated authors page

## PR Description

* This PR fixes opencv version issues in #586 

I acknowledge to have:
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`doc/doxygen-pages/changeLog_doc.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by jlblancoc** [comment]
Can you please take a look [at this](https://travis-ci.org/MRPT/mrpt/jobs/271176979#L4173), please?
Installed package is `libopencv-contrib-dev` for 2.4.8 (Ubuntu Trusty).

Thanks!

**Comment by raghavendersahdev** [comment]
Hi @jlblancoc yes that is a bug I have fixed in my [next commit](https://github.com/raghavendersahdev/mrpt/commit/280295a6443101b9057f23de678f4cd1b3c761cf), could you let me know if [my fork of mrpt-2.0-deve](https://github.com/raghavendersahdev/mrpt/tree/mrpt-2.0-devel)  compiles on your system, if it does I can open a new PR, if it does not I can fix any issues before the PR.

**Comment by raghavendersahdev** [comment]
I think [this ](https://github.com/raghavendersahdev/mrpt/blob/mrpt-2.0-devel/libs/vision/src/CFeatureExtraction_LSD_BLD.cpp#L22)should probably not give a compilation error.

**Comment by jlblancoc** [comment]
Hi! I came just to say that it also fails in Ubuntu Artful which has opencv 3.1: [log](https://launchpadlibrarian.net/335541000/buildlog_ubuntu-artful-amd64.mrpt_1%3A1.9.9~snapshot20170902-1700-git-dd92f600-artful-1~ppa1~artful_BUILDING.txt.gz). 

But it seems your patch will almost surely fix it... will apply and let's see. 

Thanks for the quick feedback!

**Comment by raghavendersahdev** [comment]
hmmm....I have this opencv:
selection_060

**Comment by raghavendersahdev** [comment]
I installed ros-kinetic, which requires opencv 3 so I think it picks up opencv 3.2, is there a way to check which version my code uses / picks up?

**Comment by jlblancoc** [comment]
Before doing more changes too quickly... 

I realized that `line_descriptor.hpp` is used in [many other places](https://github.com/MRPT/mrpt/search?utf8=%E2%9C%93&q=line_descriptor&type=)... 

> hmmm....I have this opencv:

Yes, and it builds cleanly on my local machine with opencv < 3.0. I guess this requires further investigation, right?

[Here](https://launchpad.net/~joseluisblancoc/+archive/ubuntu/mrpt/+packages) you can access to the build logs of all the failing attempts to build MRPT in different Ubuntu distros (all fail now!!). Inspecting the logs, you can see which version MRPT is picking by observing the summary printed at the end of "cmake ." (configure step).

**Comment by jlblancoc** [comment]
run `locate opencv_modules.hpp` and see its contents to check for all the `HAVE_OPENCV_*` macros.  
The same can be done for the remote PPA builders by going to the Ubuntu package archive website and clicking on "see list of files", or even downloading the .deb files and extracting them to see the contents of `locate opencv_modules.hpp` , etc. 

There must be an explanation! 

PS: Welcome to the wonder and joy of publishing a library and trying to keep it working in *tons* of platforms and distributions ;-) Kind of hell, right?

**Comment by raghavendersahdev** [comment]
Yes I think this requires further investigation. I should be including opencv checks everywhere whereever I import opencv files (in almost everyfile)? 

Alternatively can I include one check for opencv version in the [CMakeLists.txt](https://github.com/raghavendersahdev/mrpt/blob/mrpt-2.0-devel/apps/benchmarking-image-features/CMakeLists.txt) file for the benchmarking app/project and if the required version is not present the entire project can be skipped?

**Comment by raghavendersahdev** [comment]
> PS: Welcome to the wonder and joy of publishing a library and trying to keep it working in tons of platforms and distributions ;-) Kind of hell, right?

Yes I agree..!! but it sure is joy too :-)

**Comment by jlblancoc** [comment]
> I should be including opencv checks everywhere whereever I import opencv files (in almost everyfile)?

Yes. If possible, do it via the common `do_opencv_includes.h` already used in many other MRPT sources. If needed, it's better to add new stuff to that file, instead of replicating the same content over and over again in different files.

> Alternatively can I include one check for opencv version in the CMakeLists.txt file for the benchmarking app/project and if the required version is not present the entire project can be skipped?

Sure. But first we need to find out what's wrong and what's the **exact requisite** of your app. Because it compiles with 2.4.* (!!).

**Comment by raghavendersahdev** [comment]
>     Yes. If possible, do it via the common do_opencv_includes.h already used in many other MRPT sources. If needed, it's better to add new stuff to that file, instead of replicating the same content over and over again in different files.

will try to do it in this way.

this is what `locate opencv_modules.hpp` gives me:
selection_061

**Comment by jlblancoc** [comment]
If you have stuff under /usr/local/ then your builds are not reproducible
against other people with the standard OpenCV packages from the official
repos.
Try doing "sudo make uninstall" from the opencv build dir, remove the
entire mrpt build dir and start from scratch. Observe what opencv version
is printed in the final cmake summary...

Cheers

**Comment by raghavendersahdev** [comment]
I had opencv3.1 stuff in /usr/local/
Thanks, will try what you suggest and get back. Cheers

**Comment by raghavendersahdev** [comment]
I uninstalled opencv3.1 and after the cmake .. mrpt finds opencv 3.2 here:
selection_062

and when I do locate libopencv, I get the following result:
Note: there is nothing of opencv in /usr/local/
```
/opt/ros/kinetic/lib/libopencv_aruco3.so
/opt/ros/kinetic/lib/libopencv_aruco3.so.3.2
/opt/ros/kinetic/lib/libopencv_aruco3.so.3.2.0
/opt/ros/kinetic/lib/libopencv_bgsegm3.so
/opt/ros/kinetic/lib/libopencv_bgsegm3.so.3.2
.....
/usr/lib/x86_64-linux-gnu/libopencv_calib3d.so.2.4
/usr/lib/x86_64-linux-gnu/libopencv_calib3d.so.2.4.9
......
/usr/share/doc/libopencv-calib3d2.4v5
/usr/share/doc/libopencv-core2.4v5
/usr/share/doc/libopencv-features2d2.4v5

.....
/var/cache/apt/archives/libopencv-calib3d2.4v5_2.4.9.1+dfsg-1.5ubuntu1_amd64.deb
/var/cache/apt/archives/libopencv-features2d2.4v5_2.4.9.1+dfsg-1.5ubuntu1_amd64.deb
/var/cache/apt/archives/libopencv-flann2.4v5_2.4.9.1+dfsg-1.5ubuntu1_amd64.deb
/var/lib/dpkg/info/libopencv-calib3d2.4v5:amd64.list
/var/lib/dpkg/info/libopencv-calib3d2.4v5:amd64.md5sums
/var/lib/dpkg/info/libopencv-calib3d2.4v5:amd64.shlibs
/var/lib/dpkg/info/libopencv-calib3d2.4v5:amd64.triggers
.......
```
Can we figure out the requirement of the app from this output of locate. I think it should be 3.2.0, right? 
> Yes, and it builds cleanly on my local machine with opencv < 3.0. I guess this requires further investigation, right? 
Sure. But first we need to find out what's wrong and what's the exact requisite of your app. Because it compiles with 2.4.* (!!).

But as you say it built on your machine with opencv < 3.0 also, I am a little confused here.... I dont think the opencv includes of `opencv2/xfeatures2d.hpp` and `opencv2/line_descriptor.hpp` are present in opencv 2.4.*

Currently I include something like this in the benchmarking-image-features's [CMakeLists.txt](https://github.com/raghavendersahdev/mrpt/blob/mrpt-2.0-devel/apps/benchmarking-image-features/CMakeLists.txt#L6) file. Also as I have included this in the CMakeLists.txt itself, so mrpt in general should compile with any version of opencv however the app would work only with opencv 3.2. Does this sound okay ? 

I have also included some additional includes in the [do_opencv_includes.h](https://github.com/raghavendersahdev/mrpt/blob/mrpt-2.0-devel/libs/base/include/mrpt/otherlibs/do_opencv_includes.h#L40) file. In all files I am only including the `do_opencv_include.h` file and not including opencv files anywhere separately.

All opencv changes that I did are currently available in [my commits here](https://github.com/MRPT/mrpt/compare/master...raghavendersahdev:mrpt-2.0-devel)

**Comment by jlblancoc** [comment]
I'm in the process of fixing this. 

However, I realized you also used Boost (!!), which is NOT a requisite of MRPT intentionally due to its huge size and because most of its most-used functionality is now into C++11/14. Will also try to patch it. 
I also applied clang_format to your code (I assumed it was already done... probably we forgot mentioning you it and you missed that part of the "contributing to MRPT" document, since it was updated **during** the GSOC period). For all these reasons, I would recommend you re-forking (or merging MRPT/master into a new branch of yours) so your future PRs don't raise tons of conflicts.

(cc: @famoreno )

**Pull request merged**
