### PR TITLE
Addition of basic gui skeleton for benchmarking app

### PR DESCRIPTION
**Pull request by raghavendersahdev**
## Changed apps/libraries

* modified-libX
* modified-appY
* ...

## PR Description

* (*REMOVE THIS LINE IF NOT NEEDED*) This PR Closes issue #XXX
* (*REMOVE THIS LINE IF NOT NEEDED*)

---

I acknowledge to have:
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`doc/doxygen-pages/changeLog_doc.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by jolting** [comment]
You opened the pull request to the wrong branch.

Also merge description looks incomplete.

**Comment by jolting** [comment]
You should probably rebase your changed on the mrpt-2.0 branch.

```
git clone https://github.com/raghavendersahdev/mrpt.git
cd mrpt
git checkout -b image-features
git remote add MRPT https://github.com/MRPT/mrpt.git
git fetch MRPT
git rebase MRPT/mrpt-2.0-devel
```

**Comment by jolting** [comment]
Also please take all those commits and squash them into one with a good commit message.

You can do this wit the -i option when doing the rebase.

**Comment by jlblancoc** [comment]
I was to make **exactly** the same comments that "jolting" already did above... can't add anything else... Take his advice!

Well... actually yes, I can add some more comments :- )
If this PR is just to evaluate your work as part of GSoC, there is no need to open (a new one) at this moment: you can notify the mentors in your project issue ticket (in the other repo) when you feel your code is ready for inspection and/or testing, and they/we can easily checkout from your fork. 

If you want to contribute to this main repo just one part of your changes (because they affect the common CMake scripts, etc.), please let us know and we'll try to open a PR for just that changes, ok? 

Have a nice weekend!

**Comment by raghavendersahdev** [comment]
Thanks "jlblancoc" and "jolting" for the advice, actually this pull request is just to evaluate my work as a part of GSoC. I have not made any changes to any Common CMake scripts, etc. So I think I wont make a pull request for now. I will notify the mentors in the my project issue ticket in the other repo.
I will merge all the commits as a single commit  message. 
Actually I am used to use the GUI in git for commits which I think is a bad habit. I will get used to the command line for doing the same. :-)

**Pull request closed without merging**
