### PR TITLE
fix examples

### PR DESCRIPTION
**Pull request by jolting**
working from the bottom of the list of examples to the top.

I acknowledge to have:
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`doc/doxygen-pages/changeLog_doc.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by jolting** [comment]
Meet in the middle and leave this PR open.

**Comment by jlblancoc** [comment]
Didn't saw this until right now, sorry! I've been fixing examples directly pushing to `dev-fix-examples`, from top to bottom so hopefully our conflicts are minimal to none. 
I'll leave this PR open and switch to another task now. 

After we fix all examples, I was thinking of extending the clang-format scripts (and travis checks) to the `samples` directory as well, don't you agree? 

Also, when doing the final merge to `master`, I think a squash (or at least an interactive rebasing to minimize the number of commits) would be desirable, right?

Night! ;-)

**Comment by jlblancoc** [comment]
Last commit on my side: https://github.com/MRPT/mrpt/commit/3ede412d691c142351d79bec461578f3d07e6bb8

**Comment by jolting** [comment]
Squash is good. I figured you were working in that order.

**Pull request merged**
