### PR TITLE
Simplify and robustify mrpt-1.5 by using minimal subset of C++11

### LINKED ISSUE #772: MinGW x64 building issue
Hello!

I got issue compiling mrpt wint MinGW64:

cmake .. -G "MSYS Makefiles" - ok
mingw32-make:
`$ make
Scanning dependencies of target EP_octomap
[  0%] Creating directories for 'EP_octomap'
[  0%] Performing download step (download, verify and extract) for 'EP_octomap'
-- Downloading...
   dst='D:/Programming/libs/mrpt-1.5.6/build/EP_octomap-prefix/src/devel.zip'
   timeout='none'
-- Using src='https://github.com/MRPT/octomap/archive/devel.zip'
-- Downloading... done
-- extracting...
     src='D:/Programming/libs/mrpt-1.5.6/build/EP_octomap-prefix/src/devel.zip'
     dst='D:/Programming/libs/mrpt-1.5.6/build/otherlibs/octomap'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  0%] No patch step for 'EP_octomap'
[  0%] No update step for 'EP_octomap'
[  1%] Performing configure step for 'EP_octomap'
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: D:/Programming/tools/msys2/mingw64/bin/gcc.exe
-- Check for working C compiler: D:/Programming/tools/msys2/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/Programming/tools/msys2/mingw64/bin/g++.exe
-- Check for working CXX compiler: D:/Programming/tools/msys2/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

-- octomap building as Release
-- Found Doxygen: C:/Program Files/doxygen/bin/doxygen.exe (found version "1.8.10") found components:  doxygen missing components:  dot

-- Compile octomap using: make
-- Install octomap using: make install
--     (be sure to set the correct CMAKE_INSTALL_PREFIX before)
-- Compile API-documentation using: make docs

-- Configuring done
-- Generating done
-- Build files have been written to: D:/Programming/libs/mrpt-1.5.6/build/EP_octomap-prefix/src/EP_octomap-build
[  1%] Performing build step for 'EP_octomap'
Scanning dependencies of target octomath-static
[  7%] Building CXX object octomap/src/math/CMakeFiles/octomath-static.dir/Vector3.cpp.obj
[ 14%] Building CXX object octomap/src/math/CMakeFiles/octomath-static.dir/Quaternion.cpp.obj
[ 21%] Building CXX object octomap/src/math/CMakeFiles/octomath-static.dir/Pose6D.cpp.obj
[ 28%] Linking CXX static library /D/Programming/libs/mrpt-1.5.6/build/otherlibs/octomap/lib/liboctomath.a
[ 28%] Built target octomath-static
Scanning dependencies of target octomap-static
[ 35%] Building CXX object octomap/src/CMakeFiles/octomap-static.dir/AbstractOcTree.cpp.obj
[ 42%] Building CXX object octomap/src/CMakeFiles/octomap-static.dir/AbstractOccupancyOcTree.cpp.obj
[ 50%] Building CXX object octomap/src/CMakeFiles/octomap-static.dir/Pointcloud.cpp.obj
[ 57%] Building CXX object octomap/src/CMakeFiles/octomap-static.dir/ScanGraph.cpp.obj
[ 64%] Building CXX object octomap/src/CMakeFiles/octomap-static.dir/CountingOcTree.cpp.obj
[ 71%] Building CXX object octomap/src/CMakeFiles/octomap-static.dir/OcTree.cpp.obj
[ 78%] Building CXX object octomap/src/CMakeFiles/octomap-static.dir/OcTreeNode.cpp.obj
[ 85%] Building CXX object octomap/src/CMakeFiles/octomap-static.dir/OcTreeStamped.cpp.obj
[ 92%] Building CXX object octomap/src/CMakeFiles/octomap-static.dir/ColorOcTree.cpp.obj
[100%] Linking CXX static library /D/Programming/libs/mrpt-1.5.6/build/otherlibs/octomap/lib/liboctomap.a
[100%] Built target octomap-static
[  1%] No install step for 'EP_octomap'
[  1%] No test step for 'EP_octomap'
[  1%] Completed 'EP_octomap'
[  1%] Built target EP_octomap
Scanning dependencies of target DocumentationFiles
[  1%] Built target DocumentationFiles
[  1%] Generating C unity source libs/base/cotire/mrpt-base_C_unity.c
[  2%] Generating CXX prefix source libs/base/cotire/mrpt-base_CXX_prefix.cxx
[  2%] Generating CXX prefix header libs/base/cotire/mrpt-base_CXX_prefix.hxx
[  2%] Building CXX precompiled header libs/base/cotire/mrpt-base_CXX_prefix.hxx.gch
[  2%] Generating C prefix source libs/base/cotire/mrpt-base_C_prefix.c
[  2%] Generating C prefix header libs/base/cotire/mrpt-base_C_prefix.h
[  2%] Building C precompiled header libs/base/cotire/mrpt-base_C_prefix.h.gch
Scanning dependencies of target mrpt-base
[  2%] Building CXX object libs/base/CMakeFiles/mrpt-base.dir/src/bayes/CParticleFilter.cpp.obj
[  2%] Building CXX object libs/base/CMakeFiles/mrpt-base.dir/src/bayes/CParticleFilterCapable.cpp.obj
[  2%] Building CXX object libs/base/CMakeFiles/mrpt-base.dir/src/compress/zip.cpp.obj
[  2%] Building CXX object libs/base/CMakeFiles/mrpt-base.dir/src/math/CAtan2LookUpTable.cpp.obj
[  2%] Building CXX object libs/base/CMakeFiles/mrpt-base.dir/src/math/CHistogram.cpp.obj
[  2%] Building CXX object libs/base/CMakeFiles/mrpt-base.dir/src/math/CMatrix.cpp.obj
[  2%] Building CXX object libs/base/CMakeFiles/mrpt-base.dir/src/math/CMatrixB.cpp.obj
[  2%] Building CXX object libs/base/CMakeFiles/mrpt-base.dir/src/math/CMatrixD.cpp.obj
[  3%] Building CXX object libs/base/CMakeFiles/mrpt-base.dir/src/math/CPolygon.cpp.obj
[  3%] Building CXX object libs/base/CMakeFiles/mrpt-base.dir/src/math/CRuntimeCompiledExpression.cpp.obj
D:/Programming/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles/mrpt-base.dir/src/math/CRuntimeCompiledExpression.cpp.obj: too many sections (49113)
D:\Programming\tools\msys2\tmp\ccPuqE9n.s: Assembler messages:
D:\Programming\tools\msys2\tmp\ccPuqE9n.s: Fatal error: can't write 19 bytes to section .text of CMakeFiles/mrpt-base.dir/src/math/CRuntimeCompiledExpression.cpp.obj because: 'File too big'
D:/Programming/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles/mrpt-base.dir/src/math/CRuntimeCompiledExpression.cpp.obj: too many sections (49113)
D:\Programming\tools\msys2\tmp\ccPuqE9n.s: Fatal error: can't close CMakeFiles/mrpt-base.dir/src/math/CRuntimeCompiledExpression.cpp.obj: File too big
make[2]: *** [libs/base/CMakeFiles/mrpt-base.dir/build.make:325: libs/base/CMakeFiles/mrpt-base.dir/src/math/CRuntimeCompiledExpression.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:332: libs/base/CMakeFiles/mrpt-base.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
`

### PR DESCRIPTION
**Pull request by jlblancoc**
(W.I.P. / Request for comments)

The idea is to get rid of:
* Custom thread implementation.
* stlplus for smart pointers
* custom atomic counters

The need to enable C++11 would be propagated to user CMake scripts via `MRPTConfig.cmake`.
While some users may find the C++17 requirement for mrpt-master a bit too "on the edge", I think C++11 is now old enough to be imposed without problems.

I think it's about time for this, thinking of the next release mrpt-1.5.7. It could make sense to rename it mrpt-1.6 but it would break so many ROS pointers to the mrpt-1.5 branch... and also, I'm making the transition such as the API in user code remains untouched, so users shouldn't (ideally) notice the change, so it might be ok to keep the minor version number. (Not sure about ABI compatibility, though...)

To-do:
* [x] **important** Critical section new impl seems to `terminate()` at dtor (?)
* [x] check all examples
* [x] add c++11 flags to MRPTConfig.cmake

PS: This would also closes #772 
PS2: Comments are welcome! I will not merge (via rebase) until a few days from now.

### CODE REVIEW

**Comment by jolting** [comment]
I tentatively approve considering MRPT2.0 hasn't experienced many regressions due to this change.

>I'm making the transition such as the API in user code remains untouched

Unfortunately, stlplus details are actually exposed to the users. The biggest difference is clear() and clear_unique.

Stlplus shared pointers are really an amalgamation of weak_ptr and shared_ptr.

An std::shared_ptr equivalent to stlplus clear() doesn't exist. Arguably clear() is very dangerous anyway. Most of the time clear() can be replaced by clear_unique(), so that might not be a huge problem

clear_unique() becomes reset() with std::shared_ptr. This is the biggest breaking change.

**Comment by jlblancoc** [comment]
> Stlplus shared pointers are really an amalgamation of weak_ptr and shared_ptr.

Exactly! Specially the `clear()` was such a mistake in their design... However, they did a good job during a decade of hard work :-)

To ease the transition and still allow mrpt-1.5 user code to call `clear()` and `clear_unique()`, I'm tentatively using [this wrapper](https://github.com/MRPT/mrpt/blob/mrpt-1.5-cpp11/libs/base/include/mrpt/utils/CObject.h#L139-L158). For now, it seems to allow building 99% of existing code without problems. 
I'll continue testing during a few more days, running some apps under valgrind, etc.  to gain confidence in the new implementation before merging.

**Comment by jolting** [comment]
What about exposing reset function as well for compatibility between mrpt 1.5 and 2.0? It might help with the migration process.

**Comment by jlblancoc** [comment]
Oh, well seen! Done.

**Comment by jolting** [comment]
Ok. Let's merge this.

**Comment by jlblancoc** [comment]
This is almost done now. Remaining issues added to the top comment as a checklist.

**Comment by jolting** [comment]
SegFault is probably caused by createThread. You need to store the thread object somewhere or detach the threads.

The problem is that the thread isn't detached. If you try to destroy the thread object before the thread is terminated or detached you get std::terminate().

**Comment by jlblancoc** [comment]
Thanks.

Yes, it looks like the TThreadHandle container just needs a destructor!
Will try that...

**Comment by jolting** [comment]
https://launchpadlibrarian.net/375961430/buildlog_ubuntu-xenial-amd64.mrpt_1%3A1.5.1~snapshot201806252237-git-81a35ae-201806252250~ubuntu16.04.1_BUILDING.txt.gz

```
/<<PKGBUILDDIR>>/apps/camera-calib/CDlgCalibWizardOnline.cpp:212:11: error: ‘mrpt::hwdrivers::CCameraSensorPtr {aka class std::shared_ptr<mrpt::hwdrivers::CCameraSensor>}’ has no member named ‘clear’
```

**Comment by jlblancoc** [comment]
:+1: fixed now

**Pull request merged**
