### PR TITLE
Convert some typedefs to using

### PR DESCRIPTION
**Pull request by jolting**
I didn't get all typedefs, but it's a start.

---

I acknowledge to have:
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`doc/doxygen-pages/changeLog_doc.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by jlblancoc** [comment]
wow, great! I manually changed a few of them, but clearly not enough... 

cc: #66

**Comment by jlblancoc** [comment]
Also, many complex typedefs and cumbersome for() loops **could** be converted to `auto` and ranges. I already changed a few as I stepped into them, but nothing systematic yet. Also, in some cases it might be informative to leave the real types instead of `auto` (mainly, in heavily template-based code where it's easy to lose grip).

**Comment by jolting** [comment]
Most of these were done using a sed replacement.

4935 remaining typedefs, but that includes some of the otherlibs, which I avoided.
22.5% of remaining typedefs are in exprtk.hpp

Also my sed replacement trick missed all the multi-line typedef and the function typedefs.

**Comment by jlblancoc** [comment]
> Also my sed replacement trick missed all the multi-line typedef and the function typedefs.

I'm annoyed by how hard it seems to be to run regex replacements when dealing with multilines... (sigh) 
After much wasted time trying it with command line tools and with Atom, the best similar thing I found (though, not 100% regex compatible) is Notepad++... a Windows GUI tool :-( I feel like I must be missing "The Easy Way" (!?)

**Pull request merged**
