### PR TITLE
More constexpr in light geom

### PR DESCRIPTION
**Pull request by jolting**

### CODE REVIEW

**Comment by jolting** [comment]
Hmmm. I think this should be supported in c++14. Looks like the version of gcc we are using disagrees.

**Comment by jolting** [comment]
C++14 should support it.

Here's one bug:
https://stackoverflow.com/questions/36489369/constexpr-non-static-member-function-with-non-constexpr-constructor-gcc-clang-d

Here's another bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67371

Very disappointing.

**Comment by jolting** [comment]
Ubuntu 18.04 is coming in April. MRPT 2.0 could target that compiler. :sweat_smile:

**Comment by jlblancoc** [comment]
Yes, it's frustrating... I've been using g++-7 in u16.04 for a long time (I can confirm your patch does build with these settings), so I would be happy of raising the requisites so we don't let gcc-5 drags us!

I've just [pushed](https://github.com/MRPT/mrpt/pull/680/commits/3f6b171f6bddfc4f65f962c5fb932134dba1089f) a patch for the README. 

But before going on with this, I think we should also clear two dependencies: 
* Travis: Could you please update the docker imgs so the u16.04 ones include gcc7? (see the commands in the patch to the readme above).
* PPA builds (I'll see if I can add the gcc-7 as a depending PPA, it should work).

**Comment by jolting** [comment]
Docker images building.

**Comment by jlblancoc** [comment]
Thanks! I restarted travis jobs, let's see...

**Comment by jlblancoc** [comment]
@jolting It [still finds](https://travis-ci.org/MRPT/mrpt/jobs/350212870) gcc-5 in the docker img in travis (?). Perhaps related to caching (CMakeCache.txt) into the container? 

I already pushed the changes to build against gcc-7 in the PPA, let's see if that one works on the next automatic PPA update...

**Comment by jolting** [comment]
What about CXX=g++-7 in the env?

**Comment by jlblancoc** [comment]
> What about CXX=g++-7 in the env?

Done now (in master). Let's wait for [this](https://launchpad.net/~joseluisblancoc/+archive/ubuntu/mrpt/+packages) to build to see if no error happens, then we can merge.

**Pull request merged**
