### PR TITLE
Mrpt 2.0 devel

### PR DESCRIPTION
**Pull request by jolting**
I acknowledge to have:
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`doc/doxygen-pages/changeLog_doc.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by jolting** [comment]
@bergercookie Now would probably be a good time to switch to MRPT-2.0 for continued development. Do you plan on submitting a pull request on the 1.5 branch before it's released?

**Comment by bergercookie** [comment]
@jolting I was developing solely based on 1.5 until now.
I'll make a final PR during the next couple of days and then switch to 2.0 altogether.

**Comment by jlblancoc** [comment]
Great move!

**Comment by jolting** [comment]
@bergercookie no date yet, but new features should probably go in 2.0 unless it's for stability. The good news is I merged your changes,  but the bad news is I haven't tested them yet.

**Pull request merged**
