### PR TITLE
GitPod is a cloud Dev environment

### PR DESCRIPTION
**Pull request by jolting**
## Changed apps/libraries

Add gitpod configuration

## PR Description

Basically VS code in the browser.
It provides some free time on a container-based build machine.
Uses mrpt/mrpt-build-env:full-focal container image.

---

I acknowledge to have:
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`doc/doxygen-pages/changeLog_doc.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by jolting** [comment]
The free setup gave me 16-cores. :-)

**Comment by jlblancoc** [comment]
Awesome!! :-) 

Can we also add eigen3? 
Is the goal having the library pre-compiled, or should one log-in and start building/editing from the terminal (as I just tried to do a moment ago)?

**Comment by jolting** [comment]
> Can we also add eigen3?
libeigen3-dev is already installed in mrpt/mrpt-build-env:full-focal

>Is the goal having the library pre-compiled,
No, although it does support a snapshot feature.

> or should one log-in and start building/editing from the terminal (as I just tried to do a moment ago)?
Yeah basically.
A dev environment with VS Code with plugins as well as the ability to collaborate with other users.

**Comment by jlblancoc** [comment]
> libeigen3-dev is already installed in mrpt/mrpt-build-env:full-focal

Oh! I guess I tried and since your PR was not merged yet, it wasn't using the custom docker image, right? So bad I didn't realize XD

@jolting Can you understand why this PR is breaking CircleCI runs?? [example](https://app.circleci.com/pipelines/github/jolting/mrpt/5/workflows/6f1ccf95-3e4d-475f-b501-33719f9a2301/jobs/265)

I'll take a leap of faith and merge anyway...

**Comment by jolting** [comment]
I was able to do a complete build in my repo. With gitpod.

I can check CCI

**Pull request merged**
