### PR TITLE
Update the ExprTk library

### PR DESCRIPTION
**Pull request by ArashPartow**

### CODE REVIEW

**Comment by jlblancoc** [comment]
All relevant unit tests passed, merging. 

Thanks! :+1:

**Comment by jlblancoc** [comment]
Just in case this was a bug (?), please check these lines:

```
/home/jlblanco/code/mrpt/libs/expr/include/mrpt/3rdparty/exprtk.hpp:1931:29: warning: declaration of ‘exponent’ shadows a previous local [-Wshadow]
                   const int exponent = static_cast<int>(-std::distance(curr, itr));
                             ^~~~~~~~
/home/jlblanco/code/mrpt/libs/expr/include/mrpt/3rdparty/exprtk.hpp:1904:14: note: shadowed declaration is here
          int exponent = 0;
              ^~~~~~~~
```

**Comment by ArashPartow** [comment]
It's a different exponent. It's essentially the power to 10 the fractional part needs to be multiplied with to make it an integer.

I'll rename it so as to make it less confusing and so as not to trigger that diagnostic. 

Thank-you for raising this issue.

**Comment by jlblancoc** [comment]
ok, thanks for clarifying :+1:

**Pull request merged**
