### PR TITLE
mrpt-graphslam: Use stream versions to suppress gcc conversion warnings on 32bit systems

### PR DESCRIPTION
**Pull request by bergercookie**
**Changed apps/libraries:** 
mrpt-graphslam

I acknowledge to have: 
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`docs/doxygen-pages/changelog.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

Use COutputLogger stream versions instead of logFmt to suppress
warning for conversion from %lu to %u on 32bit systems.

### CODE REVIEW

**Comment by jlblancoc** [comment]
I'm having gcc errors due to things like:

	MRPT_LOG_DEBUG_STREAM << ss_out;

where ss_out is a stringstream! 

Please, change them to ss_out.str(), I'm not sure how many times this error happens, but I'm sure you know your code better and can localize the error faster...

**Comment by jolting** [comment]
Would it be easier to just add an operator<< (ostream& )) ?

**Comment by bergercookie** [comment]
@jlblancoc can I reproduce these errors using clang instead of gcc on Ubuntu?

**Comment by jlblancoc** [comment]
I [just added](https://github.com/MRPT/mrpt/commit/e860c0ca3bc4741e8f5793a7c71b6cde1a0c3c3c) a specialization for operator << to handle `stringstream` , so this is solved... 
@jolting if we wanted to add a specialization as you propose, for any ostream object (far more general than stringstream), what would be the equivalent of `s.str()`? Anyway, it's probably okay to leave it as is...

**Pull request merged**
