### PR TITLE
New pimpl pattern

### PR DESCRIPTION
**Pull request by jolting**

### CODE REVIEW

**Comment by jolting** [comment]
@jlblancoc Do you know if this work on windows?

**Comment by jlblancoc** [comment]
Yes, it works like a charm! 👍 

Before merging: do you think it's worth changing the existing use cases of `core/pimpl.h` to this new scheme? Probably not...

**Comment by jolting** [comment]
I'll do that later. The hard part is to the need for a deep copy on those pointers to make those classes copyable.

**Comment by jlblancoc** [comment]
spimpl is a great discovery! 👍 
I guess propagate_const is no longer needed, right?

**Comment by jolting** [comment]
Yeah. Wasn't sure if it was keeping around. Non pimple member pointers should probably use it.

**Comment by jlblancoc** [comment]
👍 merged!

**Pull request merged**
