### PR TITLE
Use C++11 nested std::exceptions instead of custom MRPT mechanisms

### LINKED ISSUE #832: Rethink MRPT's nested exceptions mechanism using C++11
I just stumbled upon some nice set of C++11 tools:
* `throw_with_nested` 
* `std::nested_exception`
...

Perhaps they make cleaner the nested exception macros in `mrpt/core/exceptions.h`.

### PR DESCRIPTION
**Pull request by jlblancoc**
## Changed apps/libraries

* mrpt-core. The most visible change is the new `mrpt::exception_to_string(e)` utility function.
* Change in most apps to make them use the new function above.
* Add a new example & docs.
* Closes #832 

Comments?

### CODE REVIEW

**Comment by jlblancoc** [comment]
@bergercookie : any idea why [this](https://circleci.com/gh/MRPT/mrpt/337) is complaining, whereas clang-format, run locally, is happy? :worried:

**Comment by jolting** [comment]
Are you using clang-format version 8?

**Comment by jlblancoc** [comment]
El mar., 6 nov. 2018 0:44, Hunter Laux <notifications@github.com> escribió:

> Are you using clang-format version 8?
>

Not in that machine! Thanks.

I'll rebase -i

**Comment by jolting** [comment]
Seems fine to me.
https://circleci.com/gh/MRPT/mrpt/367

CircleCI privileges are based on CircleCI privileges.

**Pull request merged**
