### PR TITLE
Driver for lms 151

### PR DESCRIPTION
**Pull request by alibenD**
## Changed apps/libraries

* Added libs/hwdrivers/include/mrpt/hwdrivers/CLMS151Eth_10110.h
               libs/hwdrivers/src/CLMS151Eth_10110.cpp
* Added a test example for LMS151: samples/SICK_lms151eth_test
* Added a rawlog-grabber ini file for LMS151: share/mrpt/config_files/share/mrpt/config_files/rawlog-grabber/SICK_LMS_151_Eth.ini

## PR Description
This PR Closes issue #629 , a new driver special for SICK_LMS151_Eth different with LMS100 one has been added, registered CLMS151Eth in registerAllClasses.cpp and created new ini for LMS151Eth. Developers can test a physical device without building sample program, just via rawlog-grabber. 

This driver has been tested on a physical device(SICK LMS151_10110).  Thanks

---

I acknowledge to have:
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`doc/doxygen-pages/changeLog_doc.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by alibenD** [comment]
The rawlog-grabber test result shows as following:

```
 rawlog-grabber - Part of the MRPT
 MRPT C++ Library: MRPT 1.9.9 - Sources timestamp: 2017-12-19 09:14:16 UTC
-------------------------------------------------------------------

Output rawlog filename: ./dataset_2017-12-20_11h21m15s.rawlog
External image storage: ./dataset_2017-12-20_11h21m15s_Images

[thread_LASER1] Starting... at 50 Hz

Press any key to exit program
[C2DRangeFinderAbstract|DEBUG|11:21:16.7990] read : 21
[C2DRangeFinderAbstract|DEBUG|11:21:16.7991] message : sAN SetAccessMode 1
[C2DRangeFinderAbstract|DEBUG|11:21:17.8094] read : 42
[C2DRangeFinderAbstract|DEBUG|11:21:17.8095] message : sRA LMPscancfg 9C4 1 9C4 FFF92230 225510
[C2DRangeFinderAbstract|DEBUG|11:21:18.8121] read : 43
[C2DRangeFinderAbstract|DEBUG|11:21:18.8122] message : sRA LMPoutputRange 1 1388 FFF92230 225510
[C2DRangeFinderAbstract|DEBUG|11:21:19.8148] read : 45
[C2DRangeFinderAbstract|DEBUG|11:21:19.8149] message : sRA STlms 7 0 8 00:49:57 A 01.01.1970 0 0 0
[C2DRangeFinderAbstract|DEBUG|11:21:20.8178] read : 11
[C2DRangeFinderAbstract|DEBUG|11:21:20.8178] message : sAN Run 1
[C2DRangeFinderAbstract|DEBUG|11:21:20.8647] Laser is ready
[C2DRangeFinderAbstract|DEBUG|11:21:20.8647] Distance : OK
[C2DRangeFinderAbstract|DEBUG|11:21:20.8648] Scan Count : 1081
[C2DRangeFinderAbstract|DEBUG|11:21:20.8649] doProcessSimple Show
[C2DRangeFinderAbstract|DEBUG|11:21:20.8650] state working
[C2DRangeFinderAbstract|DEBUG|11:21:20.9086] Laser is ready
[C2DRangeFinderAbstract|DEBUG|11:21:20.9086] Distance : OK
[C2DRangeFinderAbstract|DEBUG|11:21:20.9086] Scan Count : 1081
[C2DRangeFinderAbstract|DEBUG|11:21:20.9088] doProcessSimple Show
[C2DRangeFinderAbstract|DEBUG|11:21:20.9088] state working
[C2DRangeFinderAbstract|DEBUG|11:21:20.9521] Laser is ready
[C2DRangeFinderAbstract|DEBUG|11:21:20.9522] Distance : OK
[C2DRangeFinderAbstract|DEBUG|11:21:20.9522] Scan Count : 1081
[C2DRangeFinderAbstract|DEBUG|11:21:20.9523] doProcessSimple Show
[C2DRangeFinderAbstract|DEBUG|11:21:20.9523] state working
[C2DRangeFinderAbstract|DEBUG|11:21:20.9953] Laser is ready
[C2DRangeFinderAbstract|DEBUG|11:21:20.9954] Distance : OK
[C2DRangeFinderAbstract|DEBUG|11:21:20.9954] Scan Count : 1081
[C2DRangeFinderAbstract|DEBUG|11:21:20.9956] doProcessSimple Show
[C2DRangeFinderAbstract|DEBUG|11:21:20.9956] state working
[C2DRangeFinderAbstract|DEBUG|11:21:21.0380] Laser is ready
[C2DRangeFinderAbstract|DEBUG|11:21:21.0381] Distance : OK
[C2DRangeFinderAbstract|DEBUG|11:21:21.0381] Scan Count : 1081
[C2DRangeFinderAbstract|DEBUG|11:21:21.0383] doProcessSimple Show
[C2DRangeFinderAbstract|DEBUG|11:21:21.0383] state working
[C2DRangeFinderAbstract|DEBUG|11:21:21.0812] Laser is ready
[C2DRangeFinderAbstract|DEBUG|11:21:21.0812] Distance : OK
[C2DRangeFinderAbstract|DEBUG|11:21:21.0813] Scan Count : 1081
[C2DRangeFinderAbstract|DEBUG|11:21:21.0814] doProcessSimple Show
[C2DRangeFinderAbstract|DEBUG|11:21:21.0814] state working
[C2DRangeFinderAbstract|DEBUG|11:21:21.1242] Laser is ready
[C2DRangeFinderAbstract|DEBUG|11:21:21.1243] Distance : OK
[C2DRangeFinderAbstract|DEBUG|11:21:21.1243] Scan Count : 1081
[C2DRangeFinderAbstract|DEBUG|11:21:21.1245] doProcessSimple Show
[C2DRangeFinderAbstract|DEBUG|11:21:21.1245] state working
[C2DRangeFinderAbstract|DEBUG|11:21:21.1670] Laser is ready
[C2DRangeFinderAbstract|DEBUG|11:21:21.1670] Distance : OK
[C2DRangeFinderAbstract|DEBUG|11:21:21.1670] Scan Count : 1081
[C2DRangeFinderAbstract|DEBUG|11:21:21.1672] doProcessSimple Show
[C2DRangeFinderAbstract|DEBUG|11:21:21.1672] state working
[C2DRangeFinderAbstract|DEBUG|11:21:21.2102] Laser is ready
[C2DRangeFinderAbstract|DEBUG|11:21:21.2103] Distance : OK
[C2DRangeFinderAbstract|DEBUG|11:21:21.2103] Scan Count : 1081
[C2DRangeFinderAbstract|DEBUG|11:21:21.2105] doProcessSimple Show
[C2DRangeFinderAbstract|DEBUG|11:21:21.2105] state working
[C2DRangeFinderAbstract|DEBUG|11:21:21.2544] Laser is ready
[C2DRangeFinderAbstract|DEBUG|11:21:21.2544] Distance : OK
[C2DRangeFinderAbstract|DEBUG|11:21:21.2544] Scan Count : 1081
[C2DRangeFinderAbstract|DEBUG|11:21:21.2546] doProcessSimple Show
[C2DRangeFinderAbstract|DEBUG|11:21:21.2546] state working
[2017/12/20,03:21:21.256754] Saved 5 objects.
```

**Comment by jlblancoc** [comment]
Thanks, awesome contribution!

Before merging: do we have chances of merging this new class with the existing CLMS100Eth class? If only a few parts are different, we should rewrite them with a common base class, then implement just the "decoding" or whatever methods in the derived classes... what do you think?

Avoiding code duplication is critical for maintainability and given the current large size of MRPT (!).

**Comment by alibenD** [comment]
Hi Profess Blanco, sorry for my late reply.  I totally agree with your point to avoid code duplicatin. 
Please forgive me that I would finish it about several days later since I have something emergency to do. Thank you for your time.

**Comment by jlblancoc** [comment]
Sure! No rush at all ;-)

Happy Holidays!!

**Comment by jlblancoc** [comment]
Hi @alibenD !

Did you make any progress trying to merge your changes into the existing class CLMS100Eth? If needed, close this PR and open a new one so you can git rebase or even start from scratch in your fork.

**Comment by alibenD** [comment]
Hi Professor Blanco @jlblancoc , sorry for my late reply. I would close the PR and reopen a new one to update CLMS151. Thank you for your message.

**Pull request closed without merging**
