### PR TITLE
particle filters: use values vs. pointers; enable C++17 in MRPT

### PR DESCRIPTION
**Pull request by jlblancoc**
* CProbabilityParticle now has a "storage" template param.
* SE(2) / SE(2) particle filters now use value storage instead of smart pointers for robot poses, saving huge numbers of memory allocations.
* MRPT now requires C++17 to build. See minimum compilers in updated README.md

Pending before merging: 
* [x] Take a look at what's wrong with the python bindings. I fixed many error there but the remaining one, I can't localize the problem origin...

### CODE REVIEW

**Comment by jolting** [comment]
Ok #581 is now a priority.

**Comment by jolting** [comment]
Wait for the docker hub containers to be ready and then change the travis script.

**Comment by jolting** [comment]
Looks like gtest is broken.
```
  c:\projects\mrpt\otherlibs\gtest-1.8.0\include\gtest\internal\gtest-port.h(996): error C2039: 'tr1': is not a member of 'std' [c:\projects\mrpt\build\otherlibs\gtest-1.8.0\mrptgtest.vcxproj]
```
Also the include of windows.h in mrpt\libs\gui\src\CDisplayWindow3D.cpp is causing problems.
Try `#define WIN32_LEAN_AND_MEAN` before the include.

**Comment by jolting** [comment]
I bet defining `GTEST_USE_OWN_TR1_TUPLE` will fix one of those problems.

**Comment by jolting** [comment]
I seem to recall an issue with the python bindings with c++17 on Xenial. What about just disabling the python bindings on 16.04?

**Comment by jlblancoc** [comment]
The error was so intrincated I couldn't recognize what was the actual
problem... even after years of experience with templates 😠 I'll give it
another try after having had some sleep and let's decide then!

That's the only remaining error in my last night pr.

**Comment by jlblancoc** [comment]
Please, don't merge yet. I'm fixing / avoiding the python issues. 
But the key is that the idea of converting the smart pointers inside particles to values **seems** to have decreased the execution speed of PF localization (!!). I want to double check what's going on...

**Comment by jolting** [comment]
Just added liblas-c-dev to travis full-bionic. That should enable nearly everything in Bionic.

**Comment by jolting** [comment]
>Please, don't merge yet. I'm fixing / avoiding the python issues.
But the key is that the idea of converting the smart pointers inside particles to values seems to have decreased the execution speed of PF localization (!!). I want to double check what's going on...

Probably a missing move somewhere.

**Comment by jlblancoc** [comment]
False alarm: efficiency is virtually the same in master vs. this branch. I'll later compare both to 1.5, since it seems to me (may be a delusion) that the demos were faster. 

AnywaY: we can merge now. Python errors have been isolated by commenting out the problematic code fragments. Not a real fix but allows us moving forward.

**Comment by jlblancoc** [comment]
> Probably a missing move somewhere.

I'll recheck the resampling functions anyway. But in the case of pf-localization, particles hold data as small as 3 double's, so moving or copying should be identical and should have a "negligible" cost.

**Comment by jlblancoc** [comment]
@jolting can be also delete branch dev-simpler-pose-particles-bionic? I don't want to do it just in case you have WIP over there...

**Pull request merged**
