### PR TITLE
Remove Compiler warnings 

### PR DESCRIPTION
**Pull request by mangi020**
**Changed apps/libraries:** 
*   *Describe the pull request here* ...
* (*REMOVE THIS LINE IF NOT NEEDED*) This PR Closes issue #XXX
* (*REMOVE THIS LINE IF NOT NEEDED*) 

I acknowledge to have: 
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`docs/doxygen-pages/changelog.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by mangi020** [comment]
@jlblancoc 
#258 has been closed and #259 performs the changes on master branch compilation.

**Comment by jlblancoc** [comment]
Great! Please, before accepting this, undo the changes related to `unique_ptr` or anything else requiring a C++11 compiler, since the current version of MRPT (1.X.X) should not **require** C++11. 

You can submit a separate pull request with this kind of changes to the branch `2.0-devel` if you want...

**Comment by mangi020** [comment]
@jlblancoc unique_ptr is the only c11 declaration. All other deprecated declarations/warnings were defined in c99. Hope it helps.

**Comment by jlblancoc** [comment]
All fine... thanks! :+1:

**Pull request merged**
