### PR TITLE
Replace mapbox::variant with std::variant

### PR DESCRIPTION
**Pull request by jolting**

### CODE REVIEW

**Comment by jlblancoc** [comment]
Good! Last night I was thinking about this... but thought it was optional, not variant, so didn't find it hehe

**Comment by jolting** [comment]
I think variants might potentially solve the static build problem too.

**Comment by jlblancoc** [comment]
Unfortunately, it seems to broke the examples: 
https://travis-ci.org/MRPT/mrpt/jobs/373676786#L552

Looks like `.match` was a mapbox's thing...

**Comment by jolting** [comment]
Woops. That's std::visit now.

**Comment by jlblancoc** [comment]
Thanks! Let me fix it, so I get used to these C++17 new stuff... ;-)

**Pull request merged**
