### PR TITLE
WIP: Big refactoring of matrix classes (a.k.a. "hidden Eigen")

### PR DESCRIPTION
**Pull request by jlblancoc**
This is the largest change in MRPT math classes since the introduction of Eigen years ago. 
Including Eigen headers makes compilation of user apps slow, so the new approach is to define vector & matrix containers with a minimum of Algebra functionality, but much faster to compile. The containers can still be `Eigen::Map`ed to Eigen classes as needed. 

At present, rebuilding all mrpt libs is 25% faster after this change.

Progress: 
* [X] Update all mrpt libs.
* [x] Update mrpt apps.
* [x] Double check that all unit tests pass.
* [x] Update examples.
* [x] test msvc builds
* [x] Fix regression in mahalanobis distances (?). Data association fails.
* [x] Update docs of the mrpt-math module.

Closes: #496 (after 2 years!)

PS: To be merged after rebasing/squashing.

### CODE REVIEW

**Comment by jolting** [comment]
Has it improved build times?

**Comment by jlblancoc** [comment]
> Has it improved build times?

Have been 100% focused on another project... must get back to this by next Tuesday... 
But I expect larger than 25% improvements in **overall** build times, let's see. 
(It's being an awful amount of refactoring work, hopefully it's worth at the end!)

**Comment by jlblancoc** [comment]
```
make clean
time make all -j12
```

Current master: 
```
real	9m16,601s
user	95m7,415s
sys	4m23,182s
```

This branch: 
```
real	7m21,370s
user	75m25,239s
sys	3m30,448s
```

21% time saving.

I expected it to be more, but that's something.


Build times for the apps only (as an indicator of "user" build times):

Current master: 
```
real	2m37,208s  
user	29m3,022s    = 1743s
sys	1m11,470s
```

This branch:
```
real	1m55,762s 
user	20m47,125s  = 1247s
sys	1m1,262s
```

28% time saving.

**Comment by jlblancoc** [comment]
All done! Just waiting to hear from Circle-CI, and to write the docs explaining the new classes, before merging.

**Pull request merged**
