### PR TITLE
PnP: Python bindings require python-numpy

### PR DESCRIPTION
**Pull request by jolting**
I acknowledge to have: 
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`docs/doxygen-pages/changelog.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

https://launchpadlibrarian.net/281616406/buildlog_ubuntu-xenial-amd64.mrpt_1%3A1.5.0~snapshot201608271628-git-93617af-201608291811~ubuntu16.04.1_BUILDING.txt.gz

### CODE REVIEW

**Comment by jlblancoc** [comment]
Thanks!!

**Comment by jlblancoc** [comment]
I guess I'm missing those errors in Travis because of some python-related missing pkgs... I'll change it so we immediately realize of this kind of errors in the future.

**Comment by jolting** [comment]
You won't have this problem on 14.04. My guess is that python-numpy gets installed by default. Adding python-numpy on 14.04 might be a little redundant, but shouldn't cause a problem. Is Travis building against 14.04 or 16.04?

**Comment by jlblancoc** [comment]
Against [trusty 14.04](https://github.com/MRPT/mrpt/blob/master/.travis.yml#L3), and this is setting it as a special feature to not use the **default** 12.04 (!!)

**Pull request merged**
