### PR TITLE
WIP: MSVC appveyor fixes

### PR DESCRIPTION
**Pull request by jlblancoc**
Ongoing PR with MSVC fixes in AppVeyor (not detected in local builds!)

### CODE REVIEW

**Comment by Wehrdo** [comment]
When building on MSVC 15.8.7, [this define](https://github.com/MRPT/mrpt/blob/90d18e498742335d9ccf4691ac4a17d04fecaa6b/libs/core/include/mrpt/core/aligned_allocator.h#L26) is not doing it for me. I had to add it as a project-level define in [CMakeLists.txt](https://github.com/MRPT/mrpt/blob/msvc-appveyor-fixes/CMakeLists.txt#L373).

There's also an issue with [this typename as function default argument](https://github.com/MRPT/mrpt/blob/msvc-appveyor-fixes/libs/graphslam/include/mrpt/graphslam/levmarq.h#L83), which is apparently [a known bug](https://developercommunity.visualstudio.com/content/problem/311059/vc-158-typename-in-templatized-function-default-va.html) in 15.8 that requires a workaround.

With those two fixes, I can build successfully on 15.8.

**Comment by jlblancoc** [comment]
Thanks! Could you please open a PR against this branch? 

I wanted to avoid defining more global symbols at the CMake level, since then they must be also duplicated in the MRPTConfig.cmake.in file, but if there's no other way to go... 

At least until we address #800 ...

**Comment by jlblancoc** [comment]
Unbelievable... MS released a new version of MSVC (15.8.8) today... but the regression is still there!

Just fixed those two errors on my own way with: 385742d8bbbc7bd88c289bb085cb750006b81d2d

If AppVeyor is happy, this PR can be merged to master, ok? (cc: @jolting ... your turn to merge if it's fine... bedtime in Europe ;-)

**Comment by jlblancoc** [comment]
I'll merge this one since the patch fixes some MSVC errors in AppVeyor. There are new unit test failures, but we can investigate them in a new PR...

**Pull request merged**
