### PR TITLE
Add delay load to wlanapi.dll

### PR DESCRIPTION
**Pull request by jolting**

### CODE REVIEW

**Comment by jolting** [comment]
The delay load should prevent the error as long as no unit test uses CWirelessPower.cpp

**Comment by jolting** [comment]
yep. not sure about if this fix will work though.

**Comment by jolting** [comment]
Looks like appveyor is passing now.

**Comment by jlblancoc** [comment]
Yes it worked, aleluyah! 👏👏

**Comment by jlblancoc** [comment]
Just added appveyor to the list of "required" checks for merging to master :+1:

**Pull request merged**
