### PR TITLE
mrpt-graphslam: Fix compilation error in CLoopCloser

### PR DESCRIPTION
**Pull request by bergercookie**
## Changed apps/libraries

mrpt-graphslam

## PR Description

This should most likely deal with https://github.com/MRPT/mrpt/issues/725, https://github.com/MRPT/mrpt/issues/723

---

I acknowledge to have:
* Read the [`CONTRIBUTING`](https://github.com/MRPT/mrpt/blob/master/.github/CONTRIBUTING.md) page
* Updated [`doc/doxygen-pages/changeLog_doc.h`](https://github.com/MRPT/mrpt/blob/master/doc/doxygen-pages/changeLog_doc.h) to describe these changes (if applicable)
* Updated [`AUTHORS`](https://github.com/MRPT/mrpt/blob/master/AUTHORS) (if applicable)

(Notify: @MRPT/owners )

### CODE REVIEW

**Comment by jolting** [comment]
I'll glad createFrom2D exists, but can that be changed to an explicit conversion constructor?

I would deprecate or remove that way of conversion because it is inconsistent with the c++ standard.

**Comment by jolting** [comment]
http://en.cppreference.com/w/cpp/language/using_declaration#Inheriting_constructors

**Comment by jlblancoc** [comment]
I can't remember why the `createFrom2D()` was introduced in the first term, but the `using B::B;` rule is huge! I'll check it out... :+1:

**Comment by jlblancoc** [comment]
ok, I've already checked it: this particular case cannot be mapped to a regular explicit ctor, becase it's actually a class factory with the type to be constructed determined at runtime. 
That is: it constructs an object of type `CPose3DPDF{a,b,c}` if fed with `CPosePDF{a,b,c}`. After a little thinking, I can't see any way of getting rid of the static factory method...

**Pull request merged**
