### PR TITLE
Request CMake to find OpenCV 2

### PR DESCRIPTION
**Pull request by jerry73204**
## Changed apps/libraries

- `cmakemodules/script_opencv.cmake`

## PR Description

This patch encourages CMake to find OpenCV 2 by default. Since I have multiple OpenCV installed. Especially Arch Linux allows installing `opencv` (>=4) and `opencv2-opt` in the mean time. The change makes sure build script will not find the wrong version.

### CODE REVIEW

**Comment by jlblancoc** [comment]
Thanks! I'll do some more further checking locally before merging.

**Comment by jlblancoc** [comment]
With this PR, mrpt fails to find opencv when the unique installed versions are opencv 3 or 4, which is not acceptable... 
@jerry73204 what was the problem you wanted to solve with this change? 
If it's just selecting a specific opencv version, the standard way to do it is to set the OpenCV_DIR cmake variable, which is way more generic and less invasive.

**Comment by jerry73204** [comment]
To elaborate, it's my assumption that MRPT links against OpenCV 2, even though 3 and 4 are present.
That's because I observed the MRPT includes `opencv2/*` headers.

If my assumption is wrong. It turns to another problem. In some distros, for example Arch Linux, the headers of OpenCV 4 is placed under `/usr/include/opencv4`. It would fail the compilation due to missing headers.

**Comment by jlblancoc** [comment]
Ahh, ok thanks!
Have you checked whether there's an opencv2 directory under the headers directoryr opencv4?
I guess it should be like that, since opencv headers were named opencv2 after v1, but the name remained after v3, v4,...
In that case, cmake would handle the opencv4 prefix in the include path... that's my guess, I never tested mrpt in ArchLinux...

Could @cmorgan also check this?

**Comment by jerry73204** [comment]
The [link](https://www.archlinux.org/packages/extra/x86_64/opencv/) contains the file listing of `opencv` on Arch (open link and click "View the file list for opencv" below). It shows OpenCV 4 headers are placed under `/usr/include/opencv4/opencv2/`.

**Comment by jlblancoc** [comment]
Brilliant! Then everything is as expected, and one can choose the opencv version with cmake without further changes. I was thinking on packaging mrpt for Arch once v2.0.0 is finally released, so these checks are more than welcome. 
Cheers

**Pull request closed without merging**
